services:
  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mlops_db
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  mlflow:
    image: huachitech/mlops-heart-api:v1.0
    command: mlflow server --backend-store-uri postgresql://postgres:postgres@postgres:5432/mlops_db --default-artifact-root /mlruns --host 0.0.0.0 --port 5000
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./mlruns:/mlruns

  api:
    image: huachitech/mlops-heart-api:v1.0
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mlflow

  airflow-webserver:
    image: huachitech/mlops-heart-api:v1.0
    command: airflow webserver
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/mlops_db

  airflow-scheduler:
    image: huachitech/mlops-heart-api:v1.0
    command: airflow scheduler
    depends_on:
      - postgres
    volumes:
      - ./dags:/opt/airflow/dags
    environment:
      AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@postgres:5432/mlops_db
